name: Workflow for Android APP

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OpenJDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
    
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.0
        with:
          sdk-version: '34'

      - name: Download Emulator
        uses: android-actions/setup-android@v3.2.0
        with:
          api-level: '34'
          target: 'default'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify a specific Node.js version

      # Create and start the Android emulator
      - name: Create AVD and start the emulator
        run: |
          echo "Creating emulator..."
          $ANDROID_HOME/emulator/emulator -list-avds  # List available AVDs
          echo "Starting emulator..."
          $ANDROID_HOME/emulator/emulator -avd <Your_AVD_Name> -no-snapshot-save -no-boot-anim -no-audio -no-window &
        
      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          adb devices

      - name: Verify Emulator is Running
        run: adb shell getprop init.svc.bootanim  # Ensure the boot animation has stopped
